// export default {
//   SERVER_ADD_MATERIAL_STORAGE_DATA: 'SERVER_ADD_MATERIAL_STORAGE_DATA'
// }

const constants = {
  SERVER_ADD_LEVEL_ONE_STORAGE_DATA: 'SERVER_ADD_LEVEL_ONE_STORAGE_DATA', // 新增一個倉庫原料管理第一層分類
  SERVER_GET_STORAGE_LEVEL_ONE_DATA: 'SERVER_GET_STORAGE_LEVEL_ONE_DATA', // 取得第一層的所有分類
  SERVER_PUT_STORAGE_LEVEL_ONE_DATA: 'SERVER_PUT_STORAGE_LEVEL_ONE_DATA', // 更新分類資料
  SERVER_ADD_LEVEL_TWO_STORAGE_DATA: 'SERVER_ADD_LEVEL_TWO_STORAGE_DATA', // 新增一個倉庫原料管理第二層分類
  SERVER_GET_STORAGE_LEVEL_TWO_DATA: 'SERVER_GET_STORAGE_LEVEL_TWO_DATA', // 取得第二層的所有分類
  SERVER_PUT_STORAGE_LEVEL_TWO_DATA: 'SERVER_PUT_STORAGE_LEVEL_TWO_DATA' // 更新第二層分類資料
}

module.exports = constants
